# Generated by Django 6.0.5 on 2026-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('site', models.URLField(blank=True)),
                ('interesse', models.IntegerField(default=1, help_text='Nível de interesse de 1 a 5')),
            ],
            options={
                'verbose_name_plural': 'Tecnologias',
            },
        ),
    ]
