# Generated by Django 6.0.5 on 2026-05-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('nivel', models.IntegerField(default=1, help_text='Nível de proficiência')),
            ],
            options={
                'verbose_name_plural': 'Competências',
            },
        ),
    ]
