# Generated by Django 6.0.5 on 2026-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pagina', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
