# Generated by Django 6.0.5 on 2026-05-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('duracao', models.PositiveIntegerField(help_text='Duração em anos')),
                ('instituicao', models.CharField(max_length=200)),
                ('ano_inicio', models.DateField()),
                ('ano_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Licenciaturas',
            },
        ),
    ]
