# Generated by Django 6.0.5 on 2026-05-13 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_licenciatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.licenciatura')),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
            },
        ),
    ]
