# Generated by Django 6.0.5 on 2026-05-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_unidadecurricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('classificacao', models.FloatField(blank=True, null=True)),
                ('licenciatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.licenciatura')),
            ],
            options={
                'verbose_name': 'TFC',
                'verbose_name_plural': 'TFCs',
            },
        ),
    ]
