# Generated by Django 6.0.5 on 2026-05-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('link_github', models.URLField(blank=True)),
                ('competencias', models.ManyToManyField(blank=True, to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
