# Generated by Django 6.0.5 on 2026-05-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('documentacao', models.FileField(blank=True, null=True, upload_to='makingof/')),
                ('decisoes_tomadas', models.TextField(blank=True)),
                ('erros_correcoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Making Of',
                'verbose_name_plural': 'Making Ofs',
            },
        ),
    ]
