# Generated by Django 6.0.5 on 2026-05-13 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_makingof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfc',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='licenciatura',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='nome',
        ),
        migrations.AddField(
            model_name='competencia',
            name='tipo',
            field=models.CharField(blank=True, help_text='Hard Skill ou Soft Skill', max_length=50),
        ),
        migrations.AddField(
            model_name='docente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/'),
        ),
        migrations.AddField(
            model_name='formacao',
            name='certificado_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='formacao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='ects_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='sigla',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='makingof',
            name='uso_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='unidade_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.unidadecurricular'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='autores',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tfc',
            name='imagem',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='licenciaturas',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tfc',
            name='link_pdf',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='orientadores',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tfc',
            name='palavras_chave',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tfc',
            name='sumario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='tecnologias_usadas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='titulo',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='ano_curricular',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='avaliacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='bibliografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='ects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='metodologia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='natureza',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='programa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='semestre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
